name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{0587b618-25c7-4d45-868f-556b4d828739}}
          heroku_app_name: "fidoop-fim-g39" #Must be unique in Heroku
          heroku_email: "shreypatel18@gnu.ac.in"
